Updating appFooter to include contextual footer
wet-boew/cdts-DotNetTemplates pull request #84
Opened 2024-04-30 17:48 UTC by ahmad-shahid

2024-04-30 21:05 UTC, plup2 requested changes

2024-04-30 21:05 UTC, plup2 commented on Components/Utils/ModelBuilder.cs
> +        internal ContextualFooter BuildContextualFooter
As discussed

2024-05-01 13:26 UTC, ahmad-shahid commented on Entities/Source/AppFooterGcIntranet.cs
> +        public List<IFooterSection> FooterSections { get; set; }
done

2024-05-01 13:26 UTC, ahmad-shahid commented on Components/Utils/ModelBuilder.cs
> +        internal ContextualFooter BuildContextualFooter
done

2024-05-01 14:00 UTC, plup2 approved these changes

2024-05-01 14:00 UTC, merged